/**
 * Professional PDF report briefing. Client-side only (use from browser).
 * Uses jsPDF + jspdf-autotable for layout.
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatPercent } from '@/lib/utils/formatters';
import type { MetricKey } from '@/lib/symbolic/benchmarks';
import { METRIC_LABELS } from '@/lib/symbolic/benchmarks';

export interface ReportMetric {
  key: MetricKey;
  value: number;
  unit?: string;
}

export interface ReportInsight {
  title: string;
  summary: string;
}

export interface ReportInput {
  title?: string;
  periodLabel?: string;
  avgDailyRevenue: number;
  wowPct: number;
  avgMarginPct: number;
  metrics: Record<string, number>;
  insights: ReportInsight[];
  revenueTable?: { date: string; revenue: number; margin: number }[];
}

const FONT = 'helvetica';
const TITLE_SIZE = 22;
const HEADING_SIZE = 12;
const BODY_SIZE = 10;
const MARGIN = 20;
const PAGE_W = 210;
const PAGE_H = 297;

function addFooter(doc: jsPDF, pageNum: number) {
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Generated by Koravo — ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}`,
    MARGIN,
    PAGE_H - 10
  );
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN - 15, PAGE_H - 10);
  doc.setTextColor(0, 0, 0);
}

export function generateReportPdf(input: ReportInput): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  let y = MARGIN;
  let pageNum = 1;

  // —— Title block ——
  doc.setFontSize(TITLE_SIZE);
  doc.setFont(FONT, 'bold');
  doc.text(input.title ?? 'Koravo — Performance Briefing', MARGIN, y);
  y += 10;

  doc.setFontSize(BODY_SIZE);
  doc.setFont(FONT, 'normal');
  const period = input.periodLabel ?? `Last 30 days · ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`;
  doc.text(period, MARGIN, y);
  y += 14;

  // —— Executive summary ——
  doc.setFontSize(HEADING_SIZE);
  doc.setFont(FONT, 'bold');
  doc.text('Executive summary', MARGIN, y);
  y += 8;

  doc.setFontSize(BODY_SIZE);
  doc.setFont(FONT, 'normal');
  const revenueTrend = input.wowPct >= 0 ? `Revenue is up ${input.wowPct.toFixed(1)}% week over week.` : `Revenue is down ${Math.abs(input.wowPct).toFixed(1)}% week over week.`;
  const marginNote = input.avgMarginPct >= 65 ? 'Gross margin is above target; consider premium positioning.' : 'Gross margin is below benchmark; review food cost and pricing.';
  const summaryLines = [
    `• Average daily revenue: ${formatCurrency(input.avgDailyRevenue)} (${input.periodLabel ?? 'last 30 days'}).`,
    `• ${revenueTrend}`,
    `• ${marginNote}`,
  ];
  summaryLines.forEach((line) => {
    if (y > PAGE_H - 30) {
      doc.addPage();
      pageNum++;
      y = MARGIN;
    }
    doc.text(line, MARGIN + 2, y);
    y += 6;
  });
  y += 10;

  // —— Key metrics table ——
  doc.setFontSize(HEADING_SIZE);
  doc.setFont(FONT, 'bold');
  doc.text('Key metrics', MARGIN, y);
  y += 8;

  const metricKeys: MetricKey[] = [
    'food_cost',
    'labor_cost',
    'prime_cost',
    'bev_margin',
    'avg_check',
    'waste_pct',
    'table_turns',
    'sat_score',
    'no_shows',
    'repeat_rate',
  ];
  const tableRows: string[][] = metricKeys.map((key) => {
    const v = input.metrics[key];
    const label = METRIC_LABELS[key];
    let val = '—';
    if (v != null && Number.isFinite(v)) {
      if (key === 'sat_score') val = `${v}/5`;
      else if (key === 'avg_check') val = formatCurrency(v);
      else val = formatPercent(v);
    }
    return [label, val, key === 'sat_score' ? '—' : 'Current'];
  });

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value', 'Period']],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [60, 60, 60], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    margin: { left: MARGIN },
    tableWidth: PAGE_W - 2 * MARGIN,
  });
  y = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 14;

  // —— Insights ——
  doc.setFontSize(HEADING_SIZE);
  doc.setFont(FONT, 'bold');
  doc.text('Insights & recommendations', MARGIN, y);
  y += 8;

  doc.setFont(FONT, 'normal');
  doc.setFontSize(BODY_SIZE);
  input.insights.forEach((insight) => {
    if (y > PAGE_H - 35) {
      doc.addPage();
      pageNum++;
      y = MARGIN;
    }
    doc.setFont(FONT, 'bold');
    doc.setFontSize(10);
    doc.text(insight.title, MARGIN, y);
    y += 6;
    doc.setFont(FONT, 'normal');
    doc.setFontSize(9);
    const split = doc.splitTextToSize(insight.summary, PAGE_W - 2 * MARGIN - 4);
    split.forEach((line: string) => {
      doc.text(line, MARGIN + 2, y);
      y += 5;
    });
    y += 6;
  });
  y += 8;

  // —— Revenue snapshot (optional table) ——
  if (input.revenueTable && input.revenueTable.length > 0) {
    if (y > PAGE_H - 50) {
      doc.addPage();
      pageNum++;
      y = MARGIN;
    }
    doc.setFontSize(HEADING_SIZE);
    doc.setFont(FONT, 'bold');
    doc.text('Revenue snapshot (last 14 days)', MARGIN, y);
    y += 8;

    const revRows = input.revenueTable.map((r) => [r.date, formatCurrency(r.revenue), formatPercent(r.margin)]);
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Revenue', 'Margin']],
      body: revRows,
      theme: 'grid',
      headStyles: { fillColor: [60, 60, 60], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: MARGIN },
      tableWidth: PAGE_W - 2 * MARGIN,
    });
    y = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 14;
  }

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i);
  }

  doc.save(`Koravo-Performance-Briefing-${new Date().toISOString().slice(0, 10)}.pdf`);
}
